# Copyright Cognigy GmbH. All Rights Reserved.

apiVersion: v2
appVersion: "1.32.4"
dependencies: []
deprecated: false
description: A Helm chart to deploy the Cognigy.AI Marketplace
home: https://cognigy.com
icon: https://www.cognigy.com/hubfs/Cognigy.svg
keywords:
  - cognigy
  - cognigy.ai
  - cognigy ai
  - marketplace
  - channel-connectors
  - integrations
  - add-ons
kubeVersion: "< v1.34.0-0"
maintainers:
  - name: Cognigy SRE Team
    email: sre@cognigy.com
name: cognigy-marketplace
sources:
  - https://github.com/Cognigy/cognigy-marketplace-helm-chart
type: application
version: "1.32.4"
