{{- if and (.Values.ingress.enabled) (.Values.ingress.tls.enabled) (not .Values.ingress.tls.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-traefik
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  # add base64 encoded tls certificate
  tls.crt: {{ .Values.ingress.tls.crt | b64enc | quote }}
  # add base64 encoded private key
  tls.key: {{ .Values.ingress.tls.key | b64enc | quote }}
{{- end }}
