---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cognigy-marketplace.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "cognigy-marketplace.labels" . | nindent 4 }}

data:
  {{- toYaml .Values.configmap | nindent 2 }}
