---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cognigy-marketplace.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "cognigy-marketplace.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cognigy-marketplace.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/extensions: {{ include (print $.Template.BasePath "/extensions-configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "cognigy-marketplace.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}        
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "cognigy-marketplace.fullname" . }}
          volumeMounts:
            - name: extensions
              mountPath: /app/assets
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            terminationGracePeriodSeconds: {{ .Values.livenessProbe.terminationGracePeriodSeconds }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: extensions
          configMap:
            name: {{ include "cognigy-marketplace.fullname" . }}-extensions
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
