---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cognigy-marketplace.fullname" . }}-extensions
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "cognigy-marketplace.labels" . | nindent 4 }}

data:
  extensions.json: |-
{{ .Files.Get "extensions.json" | indent 4 }}
