---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cognigy-marketplace.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "cognigy-marketplace.labels" . | nindent 4 }}
  annotations:
    {{- if (eq .Values.ingress.ingressClassName "traefik") }}
      {{- if (.Values.ingress.tls.enabled) }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
      {{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
      {{- end }}
      {{- if (.Values.ingress.marketplace.ipWhiteListMiddleware.enabled) }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-ipwhitelistmarketplace@kubernetescrd
      {{- end }}
    {{- end }}
    {{- if .Values.ingress.marketplace.annotations }}
    {{- toYaml .Values.ingress.marketplace.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- include "tlsCertificate.secretName.render" $ | nindent 2 }}
  rules:
  - host: {{ .Values.ingress.marketplace.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "cognigy-marketplace.fullname" . }}
            port:
              number: 8000
{{- end }}
