---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cognigy-marketplace.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "cognigy-marketplace.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "cognigy-marketplace.selectorLabels" . | nindent 4 }}
